local:
  service: Disk 
  root: <%= Rails.root.join("storage") %>

test: 
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV['AKIAXWHDLRUVQVFK3EFD'] %>
  secret_access_key: <%= ENV['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'] %>
  region: <%= ENV['us-east-1'] %>
  bucket: <%= ENV['javid-twitter-photo'] %>



